# Generated by Django 5.2.12 on 2026-04-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_location_created_at_alter_person_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Hora'),
        ),
    ]
