# Generated by Django 5.2.12 on 2026-04-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auditentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='log_type',
            field=models.CharField(choices=[('work', 'Work'), ('sick', 'Sick Day'), ('holiday', 'Holiday')], default='work', max_length=10, verbose_name='Tipo'),
        ),
    ]
